### ISSUE TITLE
EnablePowerBiService Parameter not available in New-AzAnalysisServicesFirewallRule

### ISSUE THREAD

**Issue by KayAndy** [mathwro/Scripts#2]
Having trouble with the section below, that uses New-AzAnalysisServicesFirewall**Rule** to enable access to the Power BI Service (if it was already enabled).

```
   if ($powerBi) {
        $Rules.Add((New-AzAnalysisServicesFirewallRule `
                    -EnablePowerBiService $true))
    }
```

EnablePowerBiService is not an available parameter for AzAnalysisServicesFirewall**Rule**  - it's only available in AzAnalysisServicesFirewall**Config** - 

If I just leave this bit out, then I end up with the Power BI Service Disabled whenever I amend a rule, and if I leave it in, I get an error.

I'm pretty new to all this, but a change that appeared to work for me was:

```
    if ($powerBi) {
            $conf = New-AzAnalysisServicesFirewallConfig -EnablePowerBiService -FirewallRule $Rules 
        }
    else {       
            $conf = New-AzAnalysisServicesFirewallConfig -FirewallRule $Rules 
        }
```

**Comment by mathwro** [comment]
Hi @KayAndy .

Nice catch, thanks. I've apparently forgotten to push that change, and it's what you are suggesting as well.
I'll test the changes and merge it as soon as possible.
